### ISSUE TITLE
Program headers not in the first page when trying to run on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [AppImageCrafters/appimage-builder#38] opened 2020-09-03 22:22 UTC
`Program headers not in the first page` error message when trying to run the contents of extracted AppImages on FreeBSD.

https://github.com/AppImage/AppImageKit/issues/98#issuecomment-682099792

Same issue with the GCompris AppImage.

Interestingly, this error does __not__ happen e.g., with the Akira AppImage that was made with go-appimage's `appimagetool -s deploy`: https://github.com/akiraux/Akira/issues/3#issuecomment-686786377

I don't have any idea yet what may be causing this. Probably something related to the way the ingredients are compiled, or something about the systems/tools they are compiled on?

(May be useful for testing: https://www.nomadbsd.org/)

**Comment by probonopd** [comment] 2020-09-03 22:33
https://github.com/freebsd/freebsd/commit/1cfd0bd0613cd9f70523467e4df52ff8a9ade484 seems to have some information on this:

@DarkHelmet433 wrote there in 1998:

> Update the ELF image activator to use some of the exec resources rather
than rolling it's own.  This means that it now uses the "safe"
exec_map_first_page() to get the ld.so headers rather than risking a panic
on a page fault failure (eg: NFS server goes down).
Since all the ELF tools go to a lot of trouble to make sure everything
lives in the first page for executables, this is a win.  __I have not seen
any ELF executable on any system where all the headers didn't fit in the
first page with lots of room to spare.__
I have been running variations of this code for some time on my pure ELF
systems.

**Comment by probonopd** [comment] 2020-09-03 22:59
Possibly caused by
https://github.com/NixOS/patchelf/issues/153

**Comment by azubieta** [comment] 2020-09-30 04:30
I'm testing using LIEF tool to change the PT_INTERP segment in ELF files. But now I'm getting an `Invalid PT_INTERP` error.

**Comment by azubieta** [comment] 2020-09-30 04:42
The Akira AppImage seems to be built on Centos or Fedora. Maybe their ld-linux version is "better" that the one shipped in Ubuntu

**Comment by azubieta** [comment] 2020-09-30 18:04
I guess that I can close this issue, as it's related to patchelf. Please feel free to reopen it if required.

The solution: use `patchelf >= 0.12`

**Closed by azubieta** 2020-09-30 18:04 UTC
Labels: block

**Comment by probonopd** [comment] 2020-09-30 18:08
This is excellent news @azubieta - but don't the new `patchelf` versions cripple our binaries?

**Comment by azubieta** [comment] 2020-09-30 18:11
The binaries ran well on FuryBSD after being patched, also they ran on all the docker containers.

Do you remember in which systems this used to happen?

**Comment by probonopd** [comment] 2020-09-30 18:16
I remember that it crippled Qt libs.

**Comment by azubieta** [comment] 2020-09-30 18:25
I'm only patching the executable (not the libraries), maybe that's why it doesn't produce any issues.

**Comment by rhaberkorn** [comment] 2025-02-25 11:19
The issue is still not resolved in FreeBSD's kernel. Should somebody come across the same issue in an existing AppImage: I managed to fix offending Linux binaries by using patchelf. Unfortunately patchelf does not write out the file unless you change something. This workaround appears to always force a rewrite of `elf-binary`, even if you don't change the rpath:

    patchelf --set-interpreter `patchelf --print-interpreter elf-binary` elf-binary
