### ISSUE TITLE
Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

### ISSUE THREAD

**Issue by SahajRana** [AppImageCrafters/appimage-builder#228] opened 2022-05-15 14:29 UTC
Hi AppImageCrafters team, thanks for this lib.

When I try installing appimage on Ubuntu 22.04 I receive the following error.

```
(blup:5876): GLib-GIO-ERROR **: 15:22:44.046: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```

It works fine on Ubuntu 20 version but not on Ubuntu 22.04. 

The bug seems to be coming from GTK-3 lib ([https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1922464](https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1922464)).

Here's the recipe I'm using to create appimage.

```
 include:
    - fonts-noto-color-emoji
    - fonts-ubuntu
    - glib-networking:amd64
    - gvfs:amd64
    - language-pack-gnome-en-base
    - libasound2-data
    - libasound2-plugins:amd64
    - libcanberra-gtk3-module:amd64
    - libcom-err2:amd64
    - libgtk-3-common
    - libidn11:amd64
    - libkeyutils1:amd64
    - liblzma5:amd64
    - libmount1:amd64
    - libnss-mdns:amd64
    - libnvidia-gl-470:amd64
    - libpcre3:amd64
    - libproxy1-plugin-gsettings:amd64
    - libproxy1-plugin-networkmanager:amd64
    - libsystemd0:amd64
    - libuuid1:amd64
    - transmission-common
    - vlc-plugin-base:amd64
    - yaru-theme-gtk
    - yaru-theme-icon
    - libvlc-dev
```

This lib `libgtk-3-common` got fix of this issue in version [gtk+3.0 3.24.25-1ubuntu4](https://launchpad.net/ubuntu/+source/gtk+3.0/3.24.25-1ubuntu4). But it seems to not be available in apt-
install i.e. 
`sudo apt-get install libgtk-3-0=3.24.25-1ubuntu4`  or 
`sudo apt-get install libgtk-3-0=3.24.33-1ubuntu1` or
`sudo apt-get install libgtk-3-common=3.24.25-1ubuntu4` 
It says this version is not available. Is there a way to resolve this?

**Comment by azubieta** [comment] 2022-05-16 16:01
You can use newer apt repositories were the issue is fixed. Just make sure you are building your app with the same binaries that get deployed in the bundle. If you are just repacking a deb file you can safely change the sources list in the recipe file.

**Comment by azubieta** [comment] 2022-12-21 19:17
Closing it a solved. Feel free to reopen if needed.

**Closed by azubieta** 2022-12-21 19:17 UTC
