### ISSUE TITLE
Not working at all under Pop OS 21.04

### ISSUE THREAD

**Issue by Yuri6037** [AppImageCrafters/appimage-builder#166] opened 2021-12-01 16:51 UTC
Hi, I've just attempted to run appimage-builder on a Rust project which depends over 3 large system libs: libavcodec, libavformat and libswscale but it failed with that:

Log:
```
INFO:main:Running main script
INFO:main:Running apt deploy
INFO:apt:apt-get update
Get:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease [18.1 kB]
Ign:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease
Get:2 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages [74.7 kB]
Fetched 92.8 kB in 1s (153 kB/s)   
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E5F8BBC5BEB10AE
W: The repository 'http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Package libgcc-s1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libkeyutils1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libselinux1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libbz2-1.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package liblzma5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package zlib1g is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libexpat1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libgpg-error0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

ERROR:root:"/usr/bin/apt-get install -y --no-install-recommends --download-only -o Debug::pkgAcquire=1 libbz2-1.0:amd64 libcom-err2:amd64 libexpat1:amd64 libgcc-s1:amd64 libgpg-error0:amd64 libkeyutils1:amd64 liblzma5:amd64 libpcre3:amd64 libselinux1:amd64 zlib1g:amd64" execution failed
ERROR:root:E: Package 'libbz2-1.0' has no installation candidate
ERROR:root:E: Unable to locate package libcom-err2:amd64
ERROR:root:E: Package 'libexpat1' has no installation candidate
ERROR:root:E: Package 'libgcc-s1' has no installation candidate
ERROR:root:E: Package 'libgpg-error0' has no installation candidate
ERROR:root:E: Package 'libkeyutils1' has no installation candidate
ERROR:root:E: Package 'liblzma5' has no installation candidate
ERROR:root:E: Unable to locate package libpcre3:amd64
ERROR:root:E: Package 'libselinux1' has no installation candidate
ERROR:root:E: Package 'zlib1g' has no installation candidate
Traceback (most recent call last):
  File "/tmp/.mount_appimaEEVoQX//usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/commands/apt_deploy.py", line 46, in __call__
    deployed_packages = apt_deploy.deploy(
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 42, in deploy
    deploy_list = self._resolve_packages_to_deploy(
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 72, in _resolve_packages_to_deploy
    deploy_list = set(self.apt_venv.resolve_packages(include_patterns))
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/venv.py", line 183, in resolve_packages
    output = self._run_apt_get_install_download_only(packages_str)
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/venv.py", line 207, in _run_apt_get_install_download_only
    shell.assert_successful_result(command)
  File "/tmp/.mount_appimaEEVoQX/usr/lib/python3.8/site-packages/appimagebuilder/utils/shell.py", line 36, in assert_successful_result
    raise RuntimeError(
RuntimeError: "/usr/bin/apt-get install -y --no-install-recommends --download-only -o Debug::pkgAcquire=1 libbz2-1.0:amd64 libcom-err2:amd64 libexpat1:amd64 libgcc-s1:amd64 libgpg-error0:amd64 libkeyutils1:amd64 liblzma5:amd64 libpcre3:amd64 libselinux1:amd64 zlib1g:amd64" execution failed with code 100
```

**Comment by azubieta** [comment] 2021-12-01 17:13
It seems that some packages changed their names from Ubuntu to Pop OS. Maybe you could try generating the recipe manually.

**Comment by goldstar611** [comment] 2022-03-02 00:47
I think the issue is the gpg key no?
```W: GPG error: http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E5F8BBC5BEB10AE
```

**Comment by azubieta** [comment] 2022-03-02 15:59
Could be, please check you have added the key url properly.

**Comment by goldstar611** [comment] 2022-03-02 17:07
In your `apt.sources` check/add/update the `key_url` I have found several examples such as [the following](http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1E5F8BBC5BEB10AE)
```yml
apt:
 arch: i386
 sources:
   - sourceline: 'deb [arch=i386] http://mx.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
     key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
#                                                                     ^^^^^^^^^^^^^^^^
```

Based on the error message, you'll need to update the key to `0x1E5F8BBC5BEB10AE`

**Comment by azubieta** [comment] 2022-04-21 17:16
Closing as solved with the @goldstar611 comment. Please feel free to reopen if needed.

**Closed by azubieta** 2022-04-21 17:16 UTC
